chance_constraint: 0.36562500000000003
margin: 0.01
horizon_cost_proportion: 0.99
coVarX: 0.001
coVarY: 0.001
max_velocity: 0.06
cleanMap: False
waypoints: 7
max_control: 0.98
cleanDist: 0.1
receding_horizon: True
start_location: 
- 0.36276416985812754
- 0.3565204743196657
- 0.0
- 0.0
environment: '[./config/small_map2.yaml]'
outFolder: '[./output/]'
horizon_polygon_size: 50
end_location: 
- 1
- 1
- 0
- 0
