chance_constraint: 0.01000001
margin: 0.1
horizon_cost_proportion: 0.99
coVarX: 0.0001
coVarY: 0.0001
max_velocity: 0.06
cleanMap: False
waypoints: 10
max_control: 0.98
cleanDist: 0.1
receding_horizon: True
start_location: 
- 0.14366311747237995
- 0.1980373817860433
- 0.0
- 0.0
environment: '[./config/map2.yaml]'
outFolder: '[./output/]'
horizon_polygon_size: 50
end_location: 
- 1
- 1
- 0
- 0
