chance_constraint: 0.140625
margin: 0.01
horizon_cost_proportion: 0.99
coVarX: 0.0001
coVarY: 0.0001
max_velocity: 0.06
cleanMap: False
waypoints: 7
max_control: 0.98
cleanDist: 0.1
receding_horizon: True
start_location: 
- 0.3606461036936795
- 0.18306396028916871
- 0.0
- 0.0
environment: '[./config/small_map2.yaml]'
outFolder: '[./output/]'
horizon_polygon_size: 50
end_location: 
- 1
- 1
- 0
- 0
