chance_constraint: 0.45703125
margin: 0.01
horizon_cost_proportion: 0.99
coVarX: 0.01
coVarY: 0.01
max_velocity: 0.14
cleanMap: False
waypoints: 3
max_control: 0.1
cleanDist: 0.1
receding_horizon: True
start_location: 
- 1.0000000000000004
- 1.0
- 0.0
- 0.0
environment: '[./config/map1.yaml]'
outFolder: '[./output/]'
horizon_polygon_size: 50
end_location: 
- 1
- 1
- 0
- 0
