chance_constraint: 0.12686567164179105
horizon_cost_proportion: 0.99
coVarX: 0.01
coVarY: 0.01
max_velocity: 0.03283582089552239
cleanMap: False
waypoints: 9
max_control: 0.1
cleanDist: 0.1
receding_horizon: True
start_location: 
- 0
- 0
- 0
- 0
environment: '[./config/newEnvi.yaml]'
outFolder: '[./output/]'
horizon_polygon_size: 50
end_location: 
- 1
- 1
- 0
- 0
