chance_constraint: 0.453125
margin: 0.01
horizon_cost_proportion: 0.99
coVarX: 0.01
coVarY: 0.01
max_velocity: 0.03
cleanMap: False
waypoints: 10
max_control: 0.98
cleanDist: 0.1
receding_horizon: True
start_location: 
- 0.21042042091988533
- 0.19222506029001746
- 0.0
- 0.0
environment: '[./config/map4.yaml]'
outFolder: '[./output/]'
horizon_polygon_size: 50
end_location: 
- 1
- 1
- 0
- 0
