chance_constraint: 0.0984375
margin: 0.01
horizon_cost_proportion: 0.99
coVarX: 0.01
coVarY: 0.01
max_velocity: 0.06
cleanMap: False
waypoints: 10
max_control: 0.98
cleanDist: 0.1
receding_horizon: True
start_location: 
- 1.003302290325805
- 1.0044929294060652
- 0.0
- 0.0
environment: '[./config/30map.yaml]'
outFolder: '[./output/]'
horizon_polygon_size: 50
end_location: 
- 1
- 1
- 0
- 0
