environment             : "[./config/newEnvi.yaml]"
chance_constraint       : 0.2
start_location          : [0,0,0,0]
end_location            : [1,1,0,0]
waypoints               : 15
max_velocity            : 0.075
max_control             : 0.075
coVarX                  : 0.01
coVarY                  : 0.01
cleanMap                : True
cleanDist               : 0.1
receding_horizon        : False
horizon_polygon_size    : 50
horizon_cost_proportion : 0.9
outFolder               : "[./output/]"
