environment             : "[./config/small_map2.yaml]"
chance_constraint       : 0.3 #0.03
margin                  : 0.01
start_location          : [0,0,0,0]
end_location            : [1,1,0,0]
waypoints               : 8
max_velocity            : 0.06 #.15
max_control             : 0.98
coVarX                  : 0.0001
coVarY                  : 0.0001
cleanMap                : False
cleanDist               : 0.1
receding_horizon        : True
horizon_polygon_size    : 50
horizon_cost_proportion : 0.99
outFolder               : "[./output/]"
